services:
  tac-who-ae-you:
    build: .
    container_name: tac-who-ae-you
    hostname: tac-who-ae-you
    ports:
      - "93:80"  # File browser
      - "48:21"  # FTP
      - "8080:8080"    # Apache2 (Secured Static Web)
      - "30000-30010:30000-30010"  # Passive FTP ports
